import { Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar"
import MobileNavbar from "./components/MobileNavbar";
import Footer from "./components/Footer";
import { LanguageProvider } from "./context/LanguageContext";


const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300","400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LanguageProvider>
    <html lang="en">
      <body
        className={`${merriweather.className}  antialiased bg-[#222] text-white   `}
      >
        <Navbar />
        <MobileNavbar />
          {children}
        <Footer />
      </body>
    </html>
    </LanguageProvider>
  );
}
